USE [master]
GO
/****** Object:  Database [BookstoreDatabase]    Script Date: 31.01.2024 19:43:46 ******/
CREATE DATABASE [BookstoreDatabase]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'BookstoreDatabase', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\BookstoreDatabase.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'BookstoreDatabase_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\BookstoreDatabase_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [BookstoreDatabase] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [BookstoreDatabase].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [BookstoreDatabase] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [BookstoreDatabase] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [BookstoreDatabase] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [BookstoreDatabase] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [BookstoreDatabase] SET ARITHABORT OFF 
GO
ALTER DATABASE [BookstoreDatabase] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [BookstoreDatabase] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [BookstoreDatabase] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [BookstoreDatabase] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [BookstoreDatabase] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [BookstoreDatabase] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [BookstoreDatabase] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [BookstoreDatabase] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [BookstoreDatabase] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [BookstoreDatabase] SET  DISABLE_BROKER 
GO
ALTER DATABASE [BookstoreDatabase] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [BookstoreDatabase] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [BookstoreDatabase] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [BookstoreDatabase] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [BookstoreDatabase] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [BookstoreDatabase] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [BookstoreDatabase] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [BookstoreDatabase] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [BookstoreDatabase] SET  MULTI_USER 
GO
ALTER DATABASE [BookstoreDatabase] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [BookstoreDatabase] SET DB_CHAINING OFF 
GO
ALTER DATABASE [BookstoreDatabase] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [BookstoreDatabase] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [BookstoreDatabase] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [BookstoreDatabase] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [BookstoreDatabase] SET QUERY_STORE = OFF
GO
USE [BookstoreDatabase]
GO
/****** Object:  Table [dbo].[Books]    Script Date: 31.01.2024 19:43:46 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Books](
	[BookId] [int] IDENTITY(1,1) NOT NULL,
	[Title] [nvarchar](255) NOT NULL,
	[Author] [nvarchar](255) NOT NULL,
	[AuthorId] [int] NULL,
	[Publisher] [nvarchar](255) NOT NULL,
	[Pages] [int] NOT NULL,
	[Genre] [nvarchar](255) NOT NULL,
	[PublicationYear] [int] NOT NULL,
	[CostPrice] [decimal](10, 2) NOT NULL,
	[SalePrice] [decimal](10, 2) NOT NULL,
	[ContinuationOf] [int] NULL,
	[SummaryPath] [nvarchar](255) NULL,
	[CoverPath] [nvarchar](255) NULL,
	[IsRecommended] [bit] NOT NULL,
	[IsDiscount] [bit] NOT NULL,
 CONSTRAINT [PK_Books] PRIMARY KEY CLUSTERED 
(
	[BookId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ShoppingCart]    Script Date: 31.01.2024 19:43:46 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ShoppingCart](
	[CartId] [int] IDENTITY(1,1) NOT NULL,
	[BookId] [int] NOT NULL,
	[UserId] [int] NOT NULL,
	[Quantity] [int] NOT NULL,
 CONSTRAINT [PK_ShoppingCart] PRIMARY KEY CLUSTERED 
(
	[CartId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Users]    Script Date: 31.01.2024 19:43:46 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Users](
	[UserId] [int] IDENTITY(1,1) NOT NULL,
	[Username] [nvarchar](50) NOT NULL,
	[Name] [nvarchar](100) NULL,
	[Email] [nvarchar](100) NULL,
	[Password] [nvarchar](255) NOT NULL,
	[BirthDate] [date] NULL,
	[AvatarPath] [nvarchar](255) NULL,
	[IsAuthor] [bit] NOT NULL,
	[IsAdmin] [bit] NOT NULL,
 CONSTRAINT [PK_Users] PRIMARY KEY CLUSTERED 
(
	[UserId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [Username_Table_1] UNIQUE NONCLUSTERED 
(
	[Username] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ShoppingCart] ADD  CONSTRAINT [DF_ShoppingCart_Quantity]  DEFAULT ((1)) FOR [Quantity]
GO
ALTER TABLE [dbo].[Users] ADD  CONSTRAINT [DF_Users_Name]  DEFAULT (N'None') FOR [Name]
GO
ALTER TABLE [dbo].[Users] ADD  CONSTRAINT [DF_Users_IsAuthor]  DEFAULT ((0)) FOR [IsAuthor]
GO
ALTER TABLE [dbo].[Users] ADD  CONSTRAINT [DF_Users_IsAdmin]  DEFAULT ((0)) FOR [IsAdmin]
GO
ALTER TABLE [dbo].[Books]  WITH CHECK ADD  CONSTRAINT [FK_Books_Users] FOREIGN KEY([AuthorId])
REFERENCES [dbo].[Users] ([UserId])
GO
ALTER TABLE [dbo].[Books] CHECK CONSTRAINT [FK_Books_Users]
GO
ALTER TABLE [dbo].[ShoppingCart]  WITH CHECK ADD  CONSTRAINT [FK_ShoppingCart_Books] FOREIGN KEY([BookId])
REFERENCES [dbo].[Books] ([BookId])
GO
ALTER TABLE [dbo].[ShoppingCart] CHECK CONSTRAINT [FK_ShoppingCart_Books]
GO
ALTER TABLE [dbo].[ShoppingCart]  WITH CHECK ADD  CONSTRAINT [FK_ShoppingCart_Users] FOREIGN KEY([UserId])
REFERENCES [dbo].[Users] ([UserId])
GO
ALTER TABLE [dbo].[ShoppingCart] CHECK CONSTRAINT [FK_ShoppingCart_Users]
GO
USE [master]
GO
ALTER DATABASE [BookstoreDatabase] SET  READ_WRITE 
GO
